config/routes.rb
Rails.application.routes.draw do
  resources :pictures
  root 'pictures#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  include PictureUploader[:image]
  validates :image, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :destroy]
  
  def new
    @picture = Picture.new
  end
  
  def create
    @picture = Picture.new(post_params)
    respond_to do |format|
      if @picture.save
        MakeSketch.call(@picture.image_url(:transformed))
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def index
    @pictures = Picture.all
  end
  
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
   
  def post_params
    params.require(:picture).permit(:image)
  end
  
  def set_picture
      @picture = Picture.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PojektInternety</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pictures/index.html.haml
%h1 Pictures Catalog
%ul
  -@pictures.each do |pic|
    =link_to image_tag(pic.image_url(:thumbnail),alt: pic.id), pic

app/views/pictures/new.html.haml
.container
  .row
    .col-sm-6.col-sm-offset-3
      %h2.text-center
        Upload your picture here! 
      = bootstrap_form_for(@picture) do |f|
        = f.file_field :image
        = f.submit

app/views/pictures/show.html.haml
- if @picture.image.present?
  = image_tag @picture.image_url(:transformed)
  = button_to 'Delete', picture_path, class: 'btn btn-danger', method: 'delete'